export default {

    FETCH_POSTS_REQUESTED: 'FETCH_POSTS_REQUESTED',
    FETCH_POSTS_SUCCEEDED: 'FETCH_POSTS_SUCCEEDE',
    FETCH_POSTS_FAILED   : 'FETCH_POSTS_FAILED',

    SEARCH_ENABLED     : 'SEARCH_ENABLED',
    SEARCH_DISABLED    : 'SEARCH_DISABLED',
    TOGGLE_SEARCH      : 'TOGGLE_SEARCH',
    SEARCH_TERM_CHANGED: 'SEARCH_TERM',
    SEARCH_CLEARED     : 'SEARCH_CLEARED',

}